#preload = /home/schaarschmidt/Pictures/Wallpaper/lost_place_2.jpg
#wallpaper = , /home/schaarschmidt/Pictures/Wallpaper/lost_place_2.jpg
#
wallpaper {
    monitor = DP-1
    path = /home/schaarschmidt/Pictures/Wallpaper/lost_place_2.jpg
    fit_mode = cover
}
splash = false
